### ISSUE TITLE
What is the function of sample captions and captions per image

### ISSUE THREAD

**Issue by laptopmutia** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#12]
I tried to understand the code but

I don't know what is the function of captions per image and sample captions and why we need that?

Utility.py
```
    # Sample captions for each image, save images to HDF5 file, and captions and their lengths to JSON files
    seed(123)
    for impaths, imcaps, split in [(train_image_paths, train_image_captions, 'TRAIN'),
                                   (val_image_paths, val_image_captions, 'VAL'),
                                   (test_image_paths, test_image_captions, 'TEST')]:

        with h5py.File(os.path.join(output_folder, split + '_IMAGES_' + base_filename + '.hdf5'), 'a') as h:
            # Make a note of the number of captions we are sampling per image
            h.attrs['captions_per_image'] = captions_per_image

            # Create dataset inside HDF5 file to store images
            images = h.create_dataset('images', (len(impaths), 3, 256, 256), dtype='uint8')

            print("\nReading %s images and captions, storing to file...\n" % split)

            enc_captions = []
            caplens = []

            for i, path in enumerate(tqdm(impaths)):

                # Sample captions
                if len(imcaps[i]) < captions_per_image:
                    captions = imcaps[i] + [choice(imcaps[i]) for _ in range(captions_per_image - len(imcaps[i]))]
                else:
                    captions = sample(imcaps[i], k=captions_per_image)

                # Sanity check
                assert len(captions) == captions_per_image

                # Read images
                img = imread(impaths[i])
                if len(img.shape) == 2:
                    img = img[:, :, np.newaxis]
                    img = np.concatenate([img, img, img], axis=2)
                img = imresize(img, (256, 256))
                img = img.transpose(2, 0, 1)
                assert img.shape == (3, 256, 256)
                assert np.max(img) <= 255

                # Save image to HDF5 file
                images[i] = img

                for j, c in enumerate(captions):
                    # Encode captions
                    enc_c = [word_map['<start>']] + [word_map.get(word, word_map['<unk>']) for word in c] + [
                        word_map['<end>']] + [word_map['<pad>']] * (max_len - len(c))

                    # Find caption lengths
                    c_len = len(c) + 2

                    enc_captions.append(enc_c)
                    caplens.append(c_len)

            # Sanity check
            assert images.shape[0] * captions_per_image == len(enc_captions) == len(caplens)

            # Save encoded captions and their lengths to JSON files
            with open(os.path.join(output_folder, split + '_CAPTIONS_' + base_filename + '.json'), 'w') as j:
                json.dump(enc_captions, j)

            with open(os.path.join(output_folder, split + '_CAPLENS_' + base_filename + '.json'), 'w') as j:
                json.dump(caplens, j)
```

Datasets.py
```
# cpi is captions per image

def __getitem__(self, i):
        # Remember, the Nth caption corresponds to the (N // captions_per_image)th image
        img = torch.FloatTensor(self.imgs[i // self.cpi] / 255.)
        if self.transform is not None:
            img = self.transform(img)

        caption = torch.LongTensor(self.captions[i])

        caplen = torch.LongTensor([self.caplens[i]])

        if self.split is 'TRAIN':
            return img, caption, caplen
        else:
            # For validation of testing, also return all 'captions_per_image' captions to find BLEU-4 score
            all_captions = torch.LongTensor(
                self.captions[((i // self.cpi) * self.cpi):(((i // self.cpi) * self.cpi) + self.cpi)])
            return img, caption, caplen, all_captions
```

**Comment by sgrvinod** [comment]
Hi, consider that our dataset contains `n_i` images, and each image has a bunch of captions. The number of captions available for each image may vary.

`captions_per_image` is a number you use so that:
- you can restrict the size of the dataset by limiting the number of captions to use per image. So if you want to use all images for training, but you want a smaller dataset, you can use only (say) 3 captions per image.
- all images have the same number of captions.

The function in `utils.py` samples the captions in the following way:
- If an image has fewer than `captions_per_image` captions available, increase the number by sampling with replacement, [similar to how it's done in NeuralTalk2](https://github.com/karpathy/neuraltalk2/blob/bd8c9d879f957e1218a8f9e1f9b663ac70375866/misc/DataLoader.lua#L112). (Note that I can use `random.choices()` to do this directly instead of using `random.choice()` in a `for` loop. I just wasn't aware of this function.) 
- Otherwise, simply choose `captions_per_image` captions without replacement, using `random.sample()`.

So, if we have `n_i` images, and `captions_per_image` captions for each image, the total number of captions in the dataset is `n_c = n_i * captions_per_image`. Since the images and captions are saved in the same order, the `i`th caption will correspond to the `i // captions_per_image`th image.

**Comment by sgrvinod** [comment]
In a few days, I'll add/update comments in the relevant portions of the code so this is clearer.

**Comment by laptopmutia** [comment]
thanks for the explanation of the code now I understand it, but I still confused though

if `captions_per_image` is limiting the caption that we use per image and `utils.py` is sampling the caption

why the final result is still the real caption(not limited to 5 and not randomized) ?

I open the `TRAIN_CAPLENS_coco_5_cap_per_img_5_min_word_freq.json`

the number is like this

```
[13, 13, 14, 10, 12, 12, 12, 13, 11, 11, 15, 11, 11, 11, 11, 14, 23, 10, 11, 11, 11, 13, 10, 11, 16, 16, 12, 13, 11, 11, 11, 12, 12, 10, 13, 15, 10, 10, 13, 13, 12, 11, 14, 13, 13, 11, 10, 10, 14, 14, 12, 10, 15, 10, 11, 12, 15, 11, 22, 12, 10, 14, 11, 13, 12, 10, 13, 14, 12, 11, 10, 10, 11, 11, 11, 13, 15, 12, 11, 10, 14, 13, 16, 14, 14, 13, 13, 10, 10, 11, 10, 27, 12, 16, 13, 10, 14, 10, 11, 13, 10, 10, 12, 11, 11, 12, 11, 12, 12, 12, 15, 19, 11, 13, 12, 18, 12, 13, 13, 12, 13, 15, 16, 12, 11, 13, 14, 12, 12, 14, 10, 10, 12, 13, 10, 12, 10, 10, 11, 11, 12, 10, 11, 11, 13, 15, 12, 10, 11, 14, 12, 10, 11, 20, 10, 11, 12, 16, 11, 10, 12, 17, 19, 13, 15, 11, 13, 13, 13, 12, 10, 13, 15, 11, 14, 11, 13, 13, 11, 14, 13, ...]
``

so is the captions file `TRAIN_CAPTIONS_coco_5_cap_per_img_5_min_word_freq.json`

```
[[9488, 1, 38, 39, 1, 40, 6, 41, 42, 43, 1, 44, 9489, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [9488, 1, 38, 39, 1, 48, 40, 43, 1, 45, 47, 44, 9489, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [9488, 1, 38, 51, 1, 44, 3, 14, 16, 17, 1, 52, 53, 9489, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [9488, 1, 38, 43, 1, 45, 46, 47, 44, 9489, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ....]
```

btw nice jakiro avatar

**Comment by sgrvinod** [comment]
The resulting files do contain the sampled captions, but they are not grouped in 5s - they are flattened lists.

So, if you have 100 images, and you sample 5 captions per image, there are a total of 500 captions, right?

Then,

`TRAIN_CAPLENS_coco_5_cap_per_img_5_min_word_freq.json` contains the true word lengths of the 500 captions. 

`TRAIN_CAPTIONS_coco_5_cap_per_img_5_min_word_freq.json` contains the 500 captions, where each caption is a list of encoded numbers. 

**So both these lists have 500 elements.** The first 5 elements in both files correspond to Image 1, the second 5 elements correspond to Image 2, etc. 

The images are stored in the HDF5 file, and there are a 100 of them. They're in the same order as the captions. For example, the 143rd element from the first two files will correspond to the 143 // 5 = 28th image from this file.

> btw nice jakiro avatar I also play dota

Thanks! It's great to hear you play too. He's my favorite hero.

**Comment by laptopmutia** [comment]
after discussing and reading your explanation
I open the karpathy json files and beautify the json
I just realize one image could have 5 captions 

my mistake is misunderstanding about the word "captions" (english is not my native tongue)
I assume the "captions" is the "token"
so when there is a image with this captions `A boy is sitting on a brightly colored chair next to a child 's book playing a guitar `

I thought the captions per image will limit it to `A boy is sitting on`

karpathy _json_file.json
``` 
{
    "sentids": [14420, 14421, 14422, 14423, 14424],
    "imgid": 2884,
    "sentences": [{
      "tokens": ["a", "boy", "is", "sitting", "on", "a", "brightly", "colored", "chair", "next", "to", "a", "child", "s", "book", "playing", "a", "guitar"],
      "raw": "A boy is sitting on a brightly colored chair next to a child 's book playing a guitar .",
      "imgid": 2884,
      "sentid": 14420
    }, {
      "tokens": ["a", "toddler", "is", "sitting", "on", "a", "red", "checked", "chair", "whilst", "playing", "a", "guitar"],
      "raw": "A toddler is sitting on a red checked chair whilst playing a guitar .",
      "imgid": 2884,
      "sentid": 14421
    }, {
      "tokens": ["a", "young", "child", "is", "sitting", "in", "a", "colorful", "chair", "with", "a", "guitar", "in", "his", "hands", "and", "a", "book", "sitting", "next", "to", "him"],
      "raw": "A young child is sitting in a colorful chair with a guitar in his hands and a book sitting next to him .",
      "imgid": 2884,
      "sentid": 14422
    }, {
      "tokens": ["a", "young", "child", "playing", "guitar", "on", "the", "chair"],
      "raw": "A young child playing guitar on the chair",
      "imgid": 2884,
      "sentid": 14423
    }, {
      "tokens": ["young", "barefoot", "boy", "playing", "a", "guitar", "setting", "in", "a", "large", "muti", "colored", "chair", "with", "a", "picture", "of", "three", "pigs", "beside", "him"],
      "raw": "Young barefoot boy playing a guitar setting in a large muti colored chair with a picture of three pigs beside him .",
      "imgid": 2884,
      "sentid": 14424
    }],
    "split": "train",
    "filename": "2201222219_8d656b0633.jpg"
  }
```

thank you so much @sgrvinod for your explanation, quick reply and this awesome tutorial 
may god bless you

**Comment by sgrvinod** [comment]
Glad you were able to figure it out, and thanks!
