### ISSUE TITLE
Error when running caption.py

### ISSUE THREAD

**Issue by shaunabdilla** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#142]
When running caption.py, with beam_search set to 3 (i've also tried 1, and 2, unsuccessfully), on a custom dataset the model has been successfully trained on, I get the following error:

```Traceback (most recent call last):
  File "caption.py", line 226, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "caption.py", line 155, in caption_image_beam_search
    i = complete_seqs_scores.index(max(complete_seqs_scores))
ValueError: max() arg is an empty sequence
```
Printing 'incomplete_inds' results in [0, 1, 2] for every iteration, whilst printing 'complete_inds' results in an empty list at every iteration. I've tried changing the image being captioned, the error persists. Any ideas?

**Comment by shaunabdilla** [comment]
Error pertains to training, not to beam_search.

**Comment by Anastasia0411** [comment]
@shaunabdilla Hi. How did you solve this problem?
