### ISSUE TITLE
About the field image caption

### ISSUE THREAD

**Issue by ZHUXUHAN** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#16]
In this field, how long have you been studying, and what publications have been published? I just started researching, can you recommend some publications ?

**Comment by ZHUXUHAN** [comment]
Thank you very much for your answers ，you have helped me a lot.

**Comment by ZHUXUHAN** [comment]
> Hi, I'm quite new to Image Captioning and computer vision in general, as my experience is mostly in NLP. In fact, one of the reasons I started doing these tutorials in computer vision is because it's a great way to learn. My academic background is in energy/environment, and not in machine/deep learning.
> 
> As you probably know, _Show, Attend, and Tell_ is one of the older models, but it's a great place to start learning. If you want to learn newer, better image captioning models, you should definitely check out the following papers -
> 
> * [Knowing When to Look: Adaptive Attention via A Visual Sentinel for Image Captioning](https://arxiv.org/abs/1612.01887)
> * [Self-critical Sequence Training for Image Captioning](https://arxiv.org/abs/1612.00563)
> * [Bottom-Up and Top-Down Attention for Image Captioning and Visual Question Answering](https://arxiv.org/abs/1707.07998)
> 
> I hope to do tutorials on them later.

Thank you very much for your answers and have helped me a lot.

**Comment by fawazsammani** [comment]
@ZHUXUHAN if you'd like to extend your knowledge, then I have extended this implementation to implement "Knowing When to Look: Adaptive Attention via A Visual Sentinel for Image Captioning". You can find it [here](https://github.com/fawazsammani/knowing-when-to-look-adaptive-attention)

**Comment by ZHUXUHAN** [comment]
Your project is very great, I will always study your latest projects, including your recommended papers, thank you very much for your guidance.
