### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by sruthiiyer** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#161]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-76206408b287> in <module>()
     97 
     98 if __name__ == '__main__':
---> 99     main()

1 frames
<ipython-input-27-5d6f3705da4f> in train(train_loader, encoder, decoder, criterion, encoder_optimizer, decoder_optimizer, epoch)
     42         # pack_padded_sequence is an easy trick to do this
     43         print("hello")
---> 44         scores, _ = pack_padded_sequence(scores, decode_lengths, batch_first=True)
     45         targets, _ = pack_padded_sequence(targets, decode_lengths, batch_first=True)
     46 

ValueError: too many values to unpack (expected 2)

In the train function of Train.py, I get a value error while doing a packed padded sequence on scores and targets. Any idea, please?.

**Comment by sruthiiyer** [comment]
I debugged. Thank you!

**Comment by sruthiiyer** [comment]
> ValueError Traceback (most recent call last) in () 97 98 if **name** == '**main**': ---> 99 main()
> 
> 1 frames in train(train_loader, encoder, decoder, criterion, encoder_optimizer, decoder_optimizer, epoch) 42 # pack_padded_sequence is an easy trick to do this 43 print("hello") ---> 44 scores, _ = pack_padded_sequence(scores, decode_lengths, batch_first=True) 45 targets, _ = pack_padded_sequence(targets, decode_lengths, batch_first=True) 46
> 
> ValueError: too many values to unpack (expected 2)
> 
> In the train function of Train.py, I get a value error while doing a packed padded sequence on scores and targets. Any idea, please?.

**Comment by 24anisha** [comment]
How did you debug this error? I am having the same problem.

**Comment by vaibhav-OG** [comment]
@sruthiiyer how did you do this?
