### ISSUE TITLE
error in computing the beam search for all images

### ISSUE THREAD

**Issue by fawazsammani** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#18]
Hello
I am getting a very weird problem. I am running the beam search function for all the images in the validation loader. However, it stops running the function at random numbers. Here in the image, it stopped at 50, another time, it stopped at 8, another time at 70, and so on.... 
The image attached demonstrates the problem.  
![untitled](https://user-images.githubusercontent.com/30661597/47614909-b69b0e80-da64-11e8-9b0c-05306d9c6ef2.png)
I even tried it with your eval.py function, and it gives the same error. Attached is the image
![capture](https://user-images.githubusercontent.com/30661597/47616303-38e0fe00-da78-11e8-9ce0-a26bbeebee62.PNG)
It also appears that the beam search function acts differently with random images. You can see that I tried to visualize the beam search for the image in which the iteration stopped at (ex: 16 in image below). 
![untitled](https://user-images.githubusercontent.com/30661597/47616721-dbe84680-da7d-11e8-8765-f00140704b71.png)
I also did a try except block to catch how many error where there, as seen below:
![try](https://user-images.githubusercontent.com/30661597/47618799-879c9100-da94-11e8-8e7b-2ef8f8b7a996.PNG)
After debugging, I found out that the reason is that the function never generated the 'end' token. Therefore, as written in the code: (if steps>50): break, the loop breaks in this case. You can see the image attached. 
![capture](https://user-images.githubusercontent.com/30661597/47641449-55864000-db23-11e8-95db-12fd148ee942.PNG)
And the funniest thing is that sometimes it completely works! You can observe the image below, where I ran this on the complete dataset, and there were no wrong ones.
![capture](https://user-images.githubusercontent.com/30661597/47644603-d5b0a380-db2b-11e8-8824-3fe812746b99.PNG)
I then re-started the program and ran the same thing again, I get 130 wrong ones! Attached below
![capturehj](https://user-images.githubusercontent.com/30661597/47649174-a99c1f00-db39-11e8-9417-3623ccfa4ce6.png)
If I visualize the predictions, I get a recursion of predictions that never ends: Attached
![capture](https://user-images.githubusercontent.com/30661597/47649761-79ee1680-db3b-11e8-8cef-70a53f6c833d.PNG)
Why is this happening? How does it work one time and doesn't the other time? Also any suggestions on how to fix it?

**Comment by fawazsammani** [comment]
Hi @sgrvinod 
I made a condition in the function that if the predictions exceed 30 in length, then increment a variable called `wrong_count`. It worked at the end but with around 3 wrong predictions (predictions that exceed 20 words) in each iteration. Ending up with around 10 wrong predictions for each epoch. the thing is why is this happening? It shouldn't happen right? Did it happened in your case?

**Comment by sgrvinod** [comment]
Okay. Nope, I don't think it happened in my case. I'll take a look.

**Comment by liuguanxiong** [comment]
I have the same problem. I am generating a report often 60 words. Is it because the sentence is too long?

**Comment by fawazsammani** [comment]
@liuguanxiong It happens mostly at the beginning. Once the model is trained, it either doesn't happen or rarely happens. However, the problem can be solved with a` try except. `Plug in all the code in the `try `block, and increment a variable `long_pred` in the except block. You'll then get how many wrong perditions. Why this is happening at the beginning is because of bad training. The model cannot predict the correct word, so it keeps on predicting wrong words that in turn lead to other wrong words that will be infinite.

**Comment by cravisjan97** [comment]
@fawazsammani @sgrvinod I am running into the same problem as stated above. Is there any way to get rid of this error?

**Comment by fawazsammani** [comment]
Hi @cravisjan97 
The `wrong` is incremented everytime the prediciotns exceeds 20 words. I think the name is confusing (sorry for that!), but maybe you should name it long_pred. So what happens once there is a prediction exceeding 20 words, is that the `smth_wrong` gets set to True. Therefore, the `else` condition will be implemented. The `else` block manually terminates the sentence with an `<end>` token, and increments the variable `wrong` to keep track on how many long predictions exceeded 20 words.

**Comment by cravisjan97** [comment]
@fawazsammani Thanks!!!

**Comment by MozhganPourKeshavarz** [comment]
@fawazsammani it works for me too, thanks a lottttt!
