### ISSUE TITLE
corpus_bleu() got an unexpected keyword argument 'emulate_multibleu'

### ISSUE THREAD

**Issue by norahsakal** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#19]
'emulate_multibleu' seems to be deprecated according to [Removed `emulate_multibleu` and `backoff` params](https://github.com/nltk/nltk/commit/764dc8f4e9756a54f12ca72fb55233f31f1eb014#diff-de624b4549ea37f3f8480d6734bd475b)
Do you have any suggestions for achieving the same performance? Have you tried using 'smoothing_function' which seems to be a replacement for 'emulate_multibleu'?

Huge thanks for an amazing repository!

**Comment by sgrvinod** [comment]
Thank you!

Thanks for the heads-up, I'm probably using an older version. From a cursory look, it appears what was previously `emulate_multibleu=True` is now the default? I'll check and confirm.

I vaguely remember I tried the smoothing functions but maybe I wasn't too sure that they were needed. I ended up just setting the `emulate_multibleu` flag to `True` because I wanted to emulate the behaviour of [`multi-bleu.perl`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl) as it's widely used.

**Comment by jason718** [comment]
I think they make it default here: https://github.com/nltk/nltk/commit/764dc8f4e9756a54f12ca72fb55233f31f1eb014

**Comment by sgrvinod** [comment]
Merged, thanks.

**Comment by kmario23** [comment]
Just to link to the current signature from the official docs: [nltk.translate.bleu_score.corpus_bleu](https://www.nltk.org/api/nltk.translate.html#nltk.translate.bleu_score.corpus_bleu)

Below is a contrived example borrowed from the docs:


```
>>> from nltk.translate.bleu_score import corpus_bleu

>>> hyp1 = ['It', 'is', 'a', 'guide', 'to', 'action', 'which',
...         'ensures', 'that', 'the', 'military', 'always',
...         'obeys', 'the', 'commands', 'of', 'the', 'party']
>>> ref1a = ['It', 'is', 'a', 'guide', 'to', 'action', 'that',
...          'ensures', 'that', 'the', 'military', 'will', 'forever',
...          'heed', 'Party', 'commands']
>>> ref1b = ['It', 'is', 'the', 'guiding', 'principle', 'which',
...          'guarantees', 'the', 'military', 'forces', 'always',
...          'being', 'under', 'the', 'command', 'of', 'the', 'Party']
>>> ref1c = ['It', 'is', 'the', 'practical', 'guide', 'for', 'the',
...          'army', 'always', 'to', 'heed', 'the', 'directions',
...          'of', 'the', 'party']

```

```
>>> hyp2 = ['he', 'read', 'the', 'book', 'because', 'he', 'was',
...         'interested', 'in', 'world', 'history']
>>> ref2a = ['he', 'was', 'interested', 'in', 'world', 'history',
...          'because', 'he', 'read', 'the', 'book']

```

     >>> list_of_references = [[ref1a, ref1b, ref1c], [ref2a]]
     >>> hypotheses = [hyp1, hyp2]
     >>> corpus_bleu(list_of_references, hypotheses)
