### ISSUE TITLE
caption.py error

### ISSUE THREAD

**Issue by ajengwulandari** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#2]
I got this error when i run the code:

Traceback (most recent call last):
  File "caption.py", line 200, in <module>
    checkpoint = torch.load(args.model)
  File "/srv/usr-virtenv/ajengw-env/lib/python3.5/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/srv/usr-virtenv/ajengw-env/lib/python3.5/site-packages/torch/serialization.py", line 459, in _load
    magic_number = pickle_module.load(f)
TypeError: file must have 'read' and 'readline' attributes

Can you help me? thanks

**Comment by sgrvinod** [comment]
I just checked and it works for my model checkpoint. Which checkpoint/pretrained model are you using? Can you check if you're pointing to the right file? My terminal command looks like this -

`python caption.py -i='../caption data/t.jpeg' -m='../BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar' --word_map='/media/ssd/caption data/WORDMAP_coco_5_cap_per_img_5_min_word_freq.json' --beam_size=5`

**Comment by ajengwulandari** [comment]
Thanks for the answer. It works

**Comment by yuhua666** [comment]
I still have a problem.
Where is word_map='/media/ssd/caption data/WORDMAP_coco_5_cap_per_img_5_min_word_freq.json'?Can I download it?
