### ISSUE TITLE
The code is wrong.....

### ISSUE THREAD

**Issue by Le-up** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#201]
There are some issues with the code, including fatal errors, making it difficult to complete the experiment well.....

**Comment by PedemonteGiacomo** [comment]
I also get usage of deprecated packages, in the train.py there are errors with unpacking and I agree that is complicated to make it work fine following only the tutorial itself.

Moreover, I see that the problem with the function pack_padded_sequence was an issue that was completed as solved #125 but for me is still a problem I have done some workarounds that made me break code further and I lost time executing all the training, and validation with untested code.
