### ISSUE TITLE
some trouble with the input files.

### ISSUE THREAD

**Issue by Goody7** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#25]
I have found that your COCO json file is different with the origin. Could you please provide the JSON file which is used to generate input files for model?

**Comment by fawazsammani** [comment]
@Goody7 It is Karpathy's Split. The author of the tutorial provided it in the Implementation part.

**Comment by sgrvinod** [comment]
Thanks @fawazsammani! Yes, it is linked as Karpathy's splits [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#dataset).
