### ISSUE TITLE
Some trouble in the model.py about fine-tuning

### ISSUE THREAD

**Issue by czhxiaohuihui** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#32]
# If fine-tuning, only fine-tune convolutional blocks 2 through 4
        for c in list(self.resnet.children())[5:]:
            for p in c.parameters():
                 p.requires_grad = fine_tune

These codes are in the models.py. From the code, it fine-tunes from 5 to the end, but the comments show only fine-tune convolutional blocks 2 through 4. Is there some contradiction？

**Comment by sgrvinod** [comment]
Hi @czhxiaohuihui, there is no contradiction.

`model.children()` returns an iterable of high-level layers present in `model`. 

`model.named_children()` returns an iterable of two-element tuples, where the first element is the name of the high-level layer and the second element is the high-level layer.

If we print the names of the high-level layers in the `ResNet101`, we get:

![image](https://user-images.githubusercontent.com/10481431/51294913-21902c00-1a3b-11e9-99e8-da63e1b59d05.png)

You can now see that the second convolutional block is at an index of 5. Therefore, we fine-tune upwards of 5.
