### ISSUE TITLE
hello,i can't find the pre-trained model you provided "BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar"

### ISSUE THREAD

**Issue by RogerNEU** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#34]
Sorry to bother you, can i get your pre-trained model "BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar"
thanks

**Comment by sgrvinod** [comment]
[Here you go!](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#model-checkpoint)

**Comment by sgrvinod** [comment]
Reopen if needed, thanks!

**Comment by L0ittle** [comment]
This url can't be open, so I want to know if you have downloaded it in this site?

> _model='BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar' --_
