### ISSUE TITLE
regarding the batch_size_t

### ISSUE THREAD

**Issue by fawazsammani** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#36]
Hi. If I wanted to manually create the output `h` for the `LSTMCell` (by just taking the memory cell `c` and running it through a `tanh` function and then multiplying it with the gate). Does the `batch_size_t` need to be included like this? Note: `c` is the output returned by the `LSTMCell`. 
```
        ht-1 = self.hidd_gate(h_prev[:batch_size_t])      
        xt = self.inp_gate(current_input)                      
        gt = F.sigmoid(ht-1+ xt )                                
        ht = gt * F.tanh(c)                   # (batch_size, hidden_size)
```
or do I need to include `batch_size_t` when activating `c` as in:
```
        ht-1 = self.hidd_gate(h_prev[:batch_size_t])      
        xt = self.inp_gate(current_input)                      
        gt = F.sigmoid(ht-1+ xt )                                
        ht = gt * F.tanh(c[batch_size_t])   # (batch_size, hidden_size)
```

**Comment by homelifes** [comment]
@fawazsammani I had some issues understanding this as well. It is quite confusing. From my understanding, regarding your question, then you should not include the `batch_size_t` because the LSTM has already generated the cell state with regard to the inputs you passed, which were filtered by `batch_size_t`. Maybe @sgrvinod can confirm

**Comment by sgrvinod** [comment]
At timestep `t`, the inputs to the `LSTMCell` are `x_t`, `h_t-1`, `c_t-1`, correct? 

All three inputs are filtered to `batch_size_t` before being fed into the `LSTMCell`, so they're all of dimensions `(batch_size_t, ...)`.

Then if I understand both of you correctly, @homelifes is correct that the cell state `c_t-1` had `batch_size_t` rows to begin with, and it continues to have that many rows when it is processed by the _forget_ and _input_ gates and also in the _output_ gate where `h_t` is generated. 

So filter all three inputs at the very beginning and proceed with the LSTM operations as usual. This is the equivalent of what's happening in the repo.

Alternatively, you could filter each of these three inputs each time they appear in the three gates, which is redundant but the same.
