### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by PabloRR100** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#39]
Hi, 

Do you have any pre-trained model that we could load to use directly for evaluation on a different dataset?

Also, does it make sense to do transfer learning in recurrent networks?

Thanks!

**Comment by sgrvinod** [comment]
Yes, there's a pretrained model [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#model-checkpoint). You could definitely try it on any data, but how well it performs would depend on how similar that data is to the MSCOCO data it was trained on. 

The most common form of transfer learning for RNNs is the use of embeddings, etc., as the _inputs_ to the RNN. I'm sure it's pretty rare that people transfer the actual parameters of the RNN. That's not to say it doesn't make sense - it's just not as universal or proven. 

I think it would definitely make sense in some cases. For example, I've used pretrained RNN sentence encoders (like [InferSent](https://github.com/facebookresearch/InferSent)) for other downstream NLP tasks. This is usually without fine-tuning though, i.e. using just its output encoding. But I don't see why we couldn't.

**Comment by PabloRR100** [comment]
Thanks you very much
