### ISSUE TITLE
regarding attention concatentation in beam search

### ISSUE THREAD

**Issue by fawazsammani** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#41]
Hi @sgrvinod ,
While exploring the beam search code, I realized something. In the line:
```
 seqs_alpha = torch.cat([seqs_alpha[prev_word_inds], alpha[prev_word_inds].unsqueeze(1)],
                               dim=1)  # (s, step+1, enc_image_size, enc_image_size)
```

you are concatenating the current alphas as follows: `alpha[prev_word_inds]`
In `prev_word_inds`, we are taking the filtered word batches (the previous words in which the current predictions belong to). For example, if the` prev_word_inds = [0,1,0]`, that means we are taking the first, second and first previous words, respectively and concatenating the attention maps which were generated according to the input of the first, second and first word. So the attention maps to be concatenated is the first, second and first, because you are using `alpha[prev_word_inds]`. But realize that if we have `[0,1,0]`, that means the previous first word `(0`) has generated 2 next words. So what you're doing is taking the SAME attention map for these 2 next words, which are completely different words. How is that possible?
Thanks!

**Comment by sgrvinod** [comment]
Hi! If I understand your question correctly, you are wondering if it makes sense that different candidate words arising from the same preceding sequence have the same attention map. 

Yes, definitely. As you know, the attention map is not based on the candidate words. It is the other way around - the candidate words were generated as likely possibilities for that particular attention map. Therefore, by definition, this will always be the case.

For example, assume we're looking at an image of a man standing next to New York City taxi.

Assume that, so far, the model has generated _`a man stands next to a`_. 

Based on this generated sequence, it decides to attend to the _taxi_ in the image and creates the corresponding attention map. Then, based on this attention map, there can be more than one valid choice for the next word in the sequence:

_`a man stands next to a car`
`a man stands next to a cab`
`a man stands next to a taxi`
`a man stands next to a yellow (...car)`
`a man stands next to a new (...york taxi)`_

All of these choices are based on the same attention map.
