### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by JohnComeon** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#44]
Could you tell me the steps to run these codes, I got a little confused.

**Comment by sgrvinod** [comment]
Hi, sorry about that. I made it clearer now - if you want to just run the code, see the instructions at the beginning of the [Training section](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#training). 

After training, you can run your model on any image by following the instructions in the [Inference section](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#inference).

**Comment by sgrvinod** [comment]
If you have any questions, let me know.
