### ISSUE TITLE
Pre-trained word embeddings

### ISSUE THREAD

**Issue by DWhettam** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#47]
How can I go about using pre-trained word embeddings for the decoder? I've [seen this issue](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/39), which mentions it, however, I'm having some difficulties finding a pre-trained model that has the right dimensions (512). How would you recommend going about it?

Thanks

**Comment by sgrvinod** [comment]
Hi @DWhettam, please see #5 regarding how to load pre-trained embeddings. You should add the following lines after you create the `decoder`, i.e. somewhere after [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/903ebcc8b64d35592b65c00d56e109d68c3f709b/train.py#L59).

```python
decoder.load_pretrained_embeddings(pretrained_embeddings)
decoder.fine_tune_embeddings(True)  # or False
```

About the dimensions, simply change the `embed_dim` parameter  [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/903ebcc8b64d35592b65c00d56e109d68c3f709b/train.py#L18) to the size of your pre-trained embeddings. This should automatically adjust the input size of the decoder LSTM as seen [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/903ebcc8b64d35592b65c00d56e109d68c3f709b/models.py#L116).

Let me know if you have any questions or difficulties with it. I should be able to respond to you within a day this time.
