### ISSUE TITLE
RuntimeError:Unable to create link(name already exists)

### ISSUE THREAD

**Issue by JohnComeon** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#48]
Hello,when I run create_input_files.py,I got errors as shown in the heading.Could you tell me how to fix this problem?

**Comment by yeulam1thienthan** [comment]
Hi, to fix this, let remove the .hdf5 files which were generated.

**Comment by JohnComeon** [comment]
> Hi, to fix this, let remove the .hdf5 files which were generated.

**Comment by JohnComeon** [comment]
Thank you very much!

**Comment by sgrvinod** [comment]
Thank you @luulinh90s. Yes, an existing hdf5 file can't be overwritten.
