### ISSUE TITLE
Do we need to use word2vec?

### ISSUE THREAD

**Issue by chaoyan1037** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#5]
Hi, I am new to the NLP techniques. I have a question about the word2vec part. As far as I know, when we use the one-hot label to represent each word, do we need to use word2vec technique to create a vector representation for each word?

**Comment by chaoyan1037** [comment]
Thanks for your answer! This really helps me a lot. I will try it later!

**Comment by sgrvinod** [comment]
I'll close this for now, please reopen if you face issues.
