### ISSUE TITLE
ValueError when evaluation

### ISSUE THREAD

**Issue by guantinglin** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#64]
Hi, 

I encounter this error and have no idea how to solve it? 
Do you have any suggestion?

I use python 3.5 and pytorch 0.4.1

Command: (evaluating with beam size 1)
```
python3 eval.py
```
```
Traceback (most recent call last):
  File "eval.py", line 179, in <module>
    print("\nBLEU-4 score @ beam size of %d is %.4f." % (beam_size, evaluate(beam_size)))
  File "eval.py", line 156, in evaluate
    i = complete_seqs_scores.index(max(complete_seqs_scores))
ValueError: max() arg is an empty sequence
```

**Comment by guantinglin** [comment]
```
Traceback (most recent call last):
  File "eval.py", line 179, in <module>
    print("\nBLEU-4 score @ beam size of %d is %.4f." % (beam_size, evaluate(beam_size)))
  File "eval.py", line 156, in evaluate
    i = complete_seqs_scores.index(max(complete_seqs_scores))
ValueError: max() arg is an empty sequence

**Comment by Ivanclj** [comment]
had same issue, would love some help!

**Comment by guantinglin** [comment]
I change the pytorch version into 0.4.0. The problem solved! 
FYR

**Comment by hubin111** [comment]
print("\nBLEU-4 score @ beam size of %d is %.4f." % (beam_size, evaluate(beam_size)))
  File "eval.py", line 156, in evaluate
    i = complete_seqs_scores.index(max(complete_seqs_scores))
ValueError: max() arg is an empty sequence

**Comment by LightGal** [comment]
Same issue while pytorch version is 0.4.0

**Comment by MozhganPourKeshavarz** [comment]
same issue :(
@LightGal , @Ivanclj  , @hubin111 could you find any solution?

**Comment by MozhganPourKeshavarz** [comment]
it works for me.
solution : [issuue18](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/18)
