### ISSUE TITLE
How to assign certain gpu（s）to train the model?

### ISSUE THREAD

**Issue by RobinWenqian** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#8]
Hi, referring to the train.py, I don't find the option to choose which gpu for training. How could I modify the code for choosing certain gpu(s) for training?

Thank you

**Comment by RobinWenqian** [comment]
and there is another wrong issue when utilizing caption.py to generate new caption for new imgs:
![image](https://user-images.githubusercontent.com/18494091/43859990-362ac7b2-9b4a-11e8-9901-561604b6459c.png)

**Comment by RobinWenqian** [comment]
I fixed it by annotating the all the 'plt' lines and just print (words). I think this may because my server doesn't have a GUI so plt are useless.

**Comment by sgrvinod** [comment]
See [here](https://pytorch.org/docs/stable/nn.html#dataparallel-layers-multi-gpu-distributed).

**Comment by RobinWenqian** [comment]
Thank so much for your reply! Really helpful!

**Comment by sgrvinod** [comment]
Glad to help! Shall I close this?

**Comment by RobinWenqian** [comment]
Certainly!
You are so kind. Thank you again.

**Comment by kangkang59812** [comment]
Actually, It has the problem to use multiGPUs . 
ERROR:
`RuntimeError: Gather got an input of invalid size: got [16, 24, 9490], but expected [16, 16, 9490]`
It seems like the code didn't put the result together when generating the sentence.

**Comment by lzy119** [comment]
> 实际上，使用multiGPU存在问题。
> 错误：
> `RuntimeError: Gather got an input of invalid size: got [16, 24, 9490], but expected [16, 16, 9490]`
> 似乎在生成句子时代码没有将结果组合在一起。
I am also using multi-gpu training, and I encountered the same problem as you. Have you solved this problem？
