### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vijaydone** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#81]
Thanks for this tutorial. It will help, if license is added to the github code for wide usage in various industry solutions.. Thanks..

**Comment by divyanshj16** [comment]
Hi, is there an update on this?
I still can't see the license.
@sgrvinod could you please add a licence.

**Comment by malpunek** [comment]
License would be great. Otherwise it's not possible to (legally) use the code in any official work/research

**Comment by sgrvinod** [comment]
@vijaydone @divyanshj16 @malpunek sorry, I apologize for not doing this earlier. I've now added the most permissive license I can find.
