### ISSUE TITLE
beam search's prev_word_inds and next_word_inds

### ISSUE THREAD

**Issue by fikrisyad** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#84]
I'm sorry if it's a stupid question, but can you help me understand this code?
```
prev_word_inds = top_k_words / vocab_size  # (s)
next_word_inds = top_k_words % vocab_size  # (s)
```

I'm wondering if `prev_word_inds` and `next_word_inds` are corresponding to the `word_map`'s indices. If so, wouldn't prev_word_inds always result in indices in the range of `s`?
Thank you for your help.

**Comment by fikrisyad** [comment]
oh, no problem, I think I already understand.

**Comment by CuongNN218** [comment]
@fikrisyad  can you explain it for me ? Why does it need to div vocab size?

**Comment by Zagreus98** [comment]
I think I got it @CuongNN218.
prev_word_inds will return the indices for the previous sequences were the next words should be added, in other words the row number from the matrix of scores

next_words_inds simply give the actual indices of words, if look earlier the scores were flatted in a vector of size k*vocabulary_size to be used  with topk(), so doing top_k_words % vocab_size will give you the word index from the vocabulary.

You can think of the matrix of scores like this ( x marks a value for the scores): 
![image](https://user-images.githubusercontent.com/81469171/124333606-62de0d00-db9d-11eb-922e-55c6713d4661.png)

**Comment by 08tjlys** [comment]
@Zagreus98 
hi，thanks for your explanation. sorry for asking
as for the matrix of scores you mentioned, i feel a little confused that you used "Decode steps" for the meaning of rows, shouldn't they all belong to the same decode step but for different k sequences?
let us say beam search k=5, so in this way, so the number of rows for your matrix is 5, each row represents possible sequences(without the next word that we are planning to add),  am i right?

**Comment by Zagreus98** [comment]
@08tjlys Yes, you are right. Sorry for the mistake. In my photo the matrix is a slice from the tensor of predictions from train.py. But the concept is the same. So yes, instead of decode steps the numbers of rows is the beam size k.
