### ISSUE TITLE
pretrained models damaged

### ISSUE THREAD

**Issue by fawazsammani** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#9]
Hi. The pretrained models you provided are available on the google drive, however, when they are downloaded they cant be opened, and when I try to open or extract, there is a message saying the files are damaged. Is it possible you can check?

Thanks

**Comment by sgrvinod** [comment]
Hi, how are you trying to open/extract them? 

I guess the `.tar` extension is misleading. They should be opened directly by PyTorch. For example, you can pass it to `caption.py` like this -

`python caption.py -i='../caption data/t.jpeg' -m='../BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar' --word_map='../WORDMAP_coco_5_cap_per_img_5_min_word_freq.json' --beam_size=1`

In any case, I've re-uploaded it along with the `word_map` JSON.

**Comment by fawazsammani** [comment]
Yes. Thanks for the answer!
Regards

**Comment by L0ittle** [comment]
Excuse me , why the pretrained models you provided are unavailable on the google drive, I can't download it anyway
