### ISSUE TITLE
Data location and WORDMAP file issue

### ISSUE THREAD

**Issue by ada-dl** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#95]
I have downloaded the coco image train2014 and val2014 datasets. 

I renamed train2014 to 'coco' and placed it in a folder with the path 'media/ssd/caption data' 
I also placed val2014 in the same folder with the path above together with dataset_coco.json file

Is this the correct location/placement and naming of the datasets to train from scratch in my machine? 

When I ran, python train.py, I get the following error: 

``` File "train.py", line 50, in main
    with open(word_map_file, 'r') as j:
FileNotFoundError: [Errno 2] No such file or directory: '/media/ssd/caption data/WORDMAP_coco_5_cap_per_img_5_min_word_freq.json'```


I am running this in the mac command line, with conda, python 3.7 

Thank you for your help.

**Comment by Sandy12345666** [comment]
Hi, I have the same problem. could you tell me how to save it? Thank you for your help.

**Comment by wxm2000** [comment]
Hi, I have the same problem too. could you please tell me how to save it? Thank you for your help.
